version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
    reviewers:
      - "mozilla-services/rapid-release-model"
  - package-ecosystem: "docker"
    schedule:
      interval: "weekly"
    directories:
    - "**/*"
